### ISSUE TITLE
1.7.0没有实质性修正，反而问题更多

### ISSUE THREAD

**Issue by lonyee1989** [TencentCloud/chat-uikit-flutter#10]
1、chat-uikit升级到1.7.0之后，TIMUIKitChat居然必传V2TimConversation conversation参数，将导致多个非消息会话列表进入时必须先代码获取V2TimConversation，造成严重的代码侵入性，如果按这种设计建议uikit项目的意义不大了；

2、bottomSheet模式下打开TIMUIKitChat，点击输入文字显示异常：出现半屏幕以上的空白区域

3、bottomSheet模式下图片/语音授权的背景说明，在拒绝状况下不能关闭必须杀端

4、发送表情问题仍没有解决 [发送表情问题]( https://github.com/TencentCloud/chat-uikit-flutter/issues/6)

**Comment by lonyee1989** [comment]
1、我们并不想在任何想要打开TIMUIKitChat之前先取V2TimConversation，而希望在进入TIMUIKitChat时候在判断获取，能否在下版本将此参数作为非必需字段
2、bottomSheet模式 请看上传相关视频
4、发送表情问题2个（越界和2个发送） 查看上传相关视频


https://user-images.githubusercontent.com/9815235/222435065-f84597aa-3808-4f9b-9f2a-615c72289e1c.mov

https://user-images.githubusercontent.com/9815235/222435114-19d605d7-3ed9-4a2f-96e2-e3d83b624f8e.mov

https://user-images.githubusercontent.com/9815235/222435141-628c89f8-241f-46fc-9664-4a35f981591a.mov

**Comment by RoleWong** [comment]
> 4、发送表情问题2个（越界和2个发送） 查看上传相关视频

表情问题，恕还是未能复现。辛苦提供下完整的测试路径，以便查询。

**Comment by RoleWong** [comment]
> 1、我们并不想在任何想要打开TIMUIKitChat之前先取V2TimConversation，而希望在进入TIMUIKitChat时候在判断获取，能否在下版本将此参数作为非必需字段 2、bottomSheet模式 请看上传相关视频 4、发送表情问题2个（越界和2个发送） 查看上传相关视频

bottomSheet，辛苦修改下我们的源码，自己适配下。在键盘高度计算那边，去掉计算即可。

**Comment by RoleWong** [comment]
> 1、我们并不想在任何想要打开TIMUIKitChat之前先取V2TimConversation，而希望在进入TIMUIKitChat时候在判断获取，能否在下版本将此参数作为非必需字段 2、bottomSheet模式 请看上传相关视频 4、发送表情问题2个（越界和2个发送） 查看上传相关视频

1. conversation字段。由于我们的Chat组件，需要多个从Conversation中取得的值，因此，这个字段我们改成为必传，望理解。以后，不再需要手动传入conversationID/Type等内容。

**Comment by RoleWong** [comment]
或者您可以加入我们的微信群，在群内沟通，相较提issue，更快捷方便。

**Comment by RoleWong** [comment]
表情面板，两个发送按钮，是产品设计的feature，上次已经跟你解释过。如果不需要的话，可以手动改源码处理
