### ISSUE TITLE
TXIMSDK_Plus_iOS  版本冲突

### ISSUE THREAD

**Issue by qflbai** [TencentCloud/chat-uikit-flutter#14]
[!] CocoaPods could not find compatible versions for pod "TXIMSDK_Plus_iOS":
  In Podfile:
    tencent_cloud_chat_sdk (from `.symlinks/plugins/tencent_cloud_chat_sdk/ios`) was resolved to 5.1.2, which depends on
      TXIMSDK_Plus_iOS (= 7.1.3925)

None of your spec sources contain a spec satisfying the dependency: `TXIMSDK_Plus_iOS (= 7.1.3925)`.

**Comment by RoleWong** [comment]
建议删除所有Pods路径和podfile.lock文件，重装Pods依赖

**Comment by RoleWong** [comment]
建议删除所有Pods路径和podfile.lock文件，重装Pods依赖
