### ISSUE TITLE
businessID type 'int' is not a subtype of type 'String'

### ISSUE THREAD

**Issue by DeliriousLee** [TencentCloud/chat-uikit-flutter#16]
由于bussinessId类型不统一，导致里面类型报错
![截屏2023-04-03 14 34 37](https://user-images.githubusercontent.com/24474112/229429740-5c37c392-64db-4bbc-afa4-9f8cc3073ef6.png)

**Comment by RoleWong** [comment]
问题已解决，下个版本修复，请关注

**Comment by RoleWong** [comment]
感谢反馈，本问题已在 2.0.0-preview.3 版本中修复。详见更新日志：Fixed an issue where the `businessID` type may not be correct.
