### ISSUE TITLE
tencent_cloud_chat_sdk和leancloud_storage版本冲突，还有很多其他冲突

### ISSUE THREAD

**Issue by Meterwhite** [TencentCloud/chat-uikit-flutter#17]
Because syncfusion_flutter_pdfviewer >=21.1.35 depends on device_info_plus ^8.1.0 and no versions of device_info_plus match >8.1.0 <9.0.0, syncfusion_flutter_pdfviewer >=21.1.35 requires device_info_plus 8.1.0.
And because device_info_plus 8.1.0 depends on ffi ^2.0.1, syncfusion_flutter_pdfviewer >=21.1.35 requires ffi ^2.0.1.
And because every version of tencent_cloud_chat_uikit depends on file_picker ^4.6.1 which depends on ffi ^1.1.2, syncfusion_flutter_pdfviewer >=21.1.35 is incompatible with tencent_cloud_chat_uikit.
So, because fofunsurvi depends on both tencent_cloud_chat_uikit any and syncfusion_flutter_pdfviewer ^21.1.37, version solving failed.
pub get failed

**Comment by RoleWong** [comment]
看了一下，主要冲突为 device_info_plus 和 ffi。
建议这两个package，在你们项目的 pubspec.yaml 里面，使用 dependencies_overiide，固定一个版本即可。
