### ISSUE TITLE
UI问题

### ISSUE THREAD

**Issue by lexoops** [TencentCloud/chat-uikit-flutter#19]
怎么去掉这个小点，这是干什么的？
![image](https://user-images.githubusercontent.com/33716494/233603102-27652ed9-c2bf-4c5c-beef-e6ded54c23cf.png)

如何能使输入栏高度一致？
![image](https://user-images.githubusercontent.com/33716494/233603234-fab433bf-1467-4dd1-a0f1-1954bf55bd39.png)
![image](https://user-images.githubusercontent.com/33716494/233603280-446bd8f2-e74e-4c07-b850-665450c6a94f.png)

**Comment by RoleWong** [comment]
1. 小点是消息已读回执哈, 可以参考: https://cloud.tencent.com/document/product/269/85905
