### ISSUE TITLE
群组管理标题栏样式不能修改

### ISSUE THREAD

**Issue by fylw** [TencentCloud/chat-uikit-flutter#20]
如添加群成员

**Comment by RoleWong** [comment]
您好, 是可以的哈. 可以参考这篇文档: https://cloud.tencent.com/document/product/269/85902. 修改appbarBgColor和appbarTextColor即可. 谢谢

**Comment by RoleWong** [comment]
您好, 是可以的哈. 可以参考这篇文档: https://cloud.tencent.com/document/product/269/85902. 修改appbarBgColor和appbarTextColor即可. 谢谢
