### ISSUE TITLE
dlopen failed: library "libtxsoundtouch.so" not found 用的flutter的demo 只要输入用户名点登录就会出现如下错误

### ISSUE THREAD

**Issue by wolfljj** [TencentCloud/chat-uikit-flutter#24]
W/SoLoader(29913): load library txsoundtouch from system path
W/SoLoader(29913): load library : java.lang.UnsatisfiedLinkError: dlopen failed: library "libtxsoundtouch.so" not found
W/SoLoader(29913): load library txsoundtouch false
W/SoLoader(29913): load library txffmpeg from system path
I/imsdk   (29913): TIM: |-server_config.cpp:260                   HandleCommercialAbilityResponse         |commercial_ability_bits:0x0000000000000000|expired_time:3600
W/SoLoader(29913): load library : java.lang.UnsatisfiedLinkError: dlopen failed: library "libtxffmpeg.so" not found
W/SoLoader(29913): load library txffmpeg false
W/SoLoader(29913): load library liteavsdk from system path
I/imsdk   (29913): TIM: |-server_config.cpp:200                   HandleServerConfigResponse              |common_version:1471|specified_version:0|expired_interval:21600|json_config:{"report_log_level":"4","report_event_type_disable":"[]","report_quality_type_disable":"[]","report_message_delay_peak":"5","network_enable_concurrent_request_iplist":"1","network_enable_local_iplist_prior":"1","enable_android_https_host_verify":"1","android_devices_rollback_https2http":"[]","support_unread_count_for_meeting":"0","db_thread_max_task_execution_time":"1000","db_file_slimming_config":"{}","network_anycast_address":"http://162.14.3.250/v4/ConfigGetSvc/GetOpenSSOIPList","disable_ios_badge_number":"0","group_attribute_request_config":"{}","cos_upload_file_size_limit":"{}","command_frequency_limit":"[]"}
W/SoLoader(29913): load library : java.lang.UnsatisfiedLinkError: dlopen failed: library "libliteavsdk.so" not found

**Comment by RoleWong** [comment]
这是腾讯有音视频的问题。辛苦前往 zhiliao.qq.com 在线社区咨询下哈，我给您拉一下音视频的同事。
