### ISSUE TITLE
tencent_cloud_uikit_core中Duration类与dart core 自带的Duration类冲突

### ISSUE THREAD

**Issue by zhixinpeng** [TencentCloud/chat-uikit-flutter#25]
![image](https://github.com/TencentCloud/chat-uikit-flutter/assets/24643457/a8f24998-47cf-467a-88be-98c84c5ba3ce)
该库从1.0.5版本开始，携带l了自定义的枚举Duration，这会导致冲突，我看该项目lock了1.0.4版本，所以没出现问题，但如果删掉lock文件安装则会出现问题
![image](https://github.com/TencentCloud/chat-uikit-flutter/assets/24643457/9b579c9a-7e71-4925-8b12-e4da73f8959f)

**Comment by RoleWong** [comment]
请重新获取项目依赖并尝试. 如果还是不行, 请手动将项目内 pubspec.lock 里面的tencent_cloud_uikit_core 升级至1.0.6版本. 谢谢
