### ISSUE TITLE
demo 跑不了

### ISSUE THREAD

**Issue by CY-ChenWeiXin** [TencentCloud/chat-uikit-flutter#28]
<img width="817" alt="image" src="https://github.com/TencentCloud/chat-uikit-flutter/assets/141915864/37994c25-0c61-4d3c-9109-59858f1e3a60">
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.5, on macOS 13.5 22G74 darwin-arm64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.82.0)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!

**Comment by RoleWong** [comment]
請問具體是什麽問題呢？

**Comment by vincepzhang** [comment]
Set ios/Podfile
 `
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['VALID_ARCHS'] = 'arm64 arm64e x86_64'
      config.build_settings['VALID_ARCHS[sdk=iphonesimulator*]'] = 'x86_64'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = "13.0"
    end
  end
end
`

**Comment by RoleWong** [comment]
请根据此说明, 修改Podfile 文件, 即可解决此问题https://cloud.tencent.com/document/product/269/70746#.E6.AD.A5.E9.AA.A41.EF.BC.9A.E5.88.9B.E5.BB.BA-flutter-.E5.BA.94.E7.94.A8.E5.B9.B6.E6.B7.BB.E5.8A.A0.E6.9D.83.E9.99.90
