### ISSUE TITLE
深色模式哪个版本可以适配呢？

### ISSUE THREAD

**Issue by NeverOvO** [TencentCloud/chat-uikit-flutter#31]
我手动改库的话工作量太大，你们不少Widget的颜色直接是定为白色的，而且每次更新后需要重新手动同步更新，请问你们的深色模式多久可以进行适配呀

**Comment by RoleWong** [comment]
目前, 深色模式, 已在最新重构的 UIKit V2 版本中实现,  欢迎体验https://www.tencentcloud.com/document/product/1047
