### ISSUE TITLE
iOS 16.7.2系统权限第一次授权弹不出来

### ISSUE THREAD

**Issue by ShareZore** [TencentCloud/chat-uikit-flutter#33]
OS 16.7.2系统权限第一次授权弹不出来，第二弹出来的弹窗跳设置看不到对应权限。测试手机iphone 12

**Comment by RoleWong** [comment]
请根据此说明, 修改Podfile 文件, 即可解决此问题https://cloud.tencent.com/document/product/269/70746#.E6.AD.A5.E9.AA.A41.EF.BC.9A.E5.88.9B.E5.BB.BA-flutter-.E5.BA.94.E7.94.A8.E5.B9.B6.E6.B7.BB.E5.8A.A0.E6.9D.83.E9.99.90
