### ISSUE TITLE
会话界面长按菜单点击多选，ui显示异常

### ISSUE THREAD

**Issue by jinjiafeng** [TencentCloud/chat-uikit-flutter#36]
![Screenshot_20240317_150007](https://github.com/TencentCloud/chat-uikit-flutter/assets/28585960/bac18eb4-bdcf-47e2-a7fc-f9601b6e00f3)

**Comment by FrankyLee-dev** [comment]
请问下怎么解决这个问题？好像是设置了useMaterial3: true,怎么修复呢？
