### ISSUE TITLE
android bug

### ISSUE THREAD

**Issue by shichonghuotian** [TencentCloud/chat-uikit-flutter#4]
在android手机上播放语音消息的时， 如果在播放的时候，手动切换语音消息， 不会执行动画， 只会播放声音。

`subscription = SoundPlayer.playStateListener(listener: (PlayState data) {
      
      if (data.playState == 'complete') {
        
        widget.chatModel.currentSelectedMsgId = "";
        // SoundPlayer.removeSoundInterruptListener();
        
      }
    });`

应该是playStateListener的状态判断有问题， 每次都会触发 complete。 （iOS手机不会这样）。

手机型号： one plus ace， android 12 （color v12.1）

**Comment by RoleWong** [comment]
问题已收到，感谢反馈。我们将在后续版本修复。谢谢～

**Comment by RoleWong** [comment]
问题已在新版修复哈~
