### ISSUE TITLE
大佬们 作为一个UI库 依赖第三方库的时候能使用一个你们当前的稳定版本不

### ISSUE THREAD

**Issue by BugFactory9527** [TencentCloud/chat-uikit-flutter#47]
今天维护一个以前的项目 发现跑不起来。。后来2.5.1+5的版本  因为现在flutter是3.19.6，然后发现是sdk库里  使用了大量的any!
<img width="1580" alt="image" src="https://github.com/user-attachments/assets/23f0d3ca-59b2-41ae-89ad-ad7703b7f5eb">
<img width="1241" alt="image" src="https://github.com/user-attachments/assets/dfe73108-3a9c-492b-8a54-d36b1eb7db4c">
<img width="1427" alt="image" src="https://github.com/user-attachments/assets/bf415c87-6995-4d67-869d-f93e4c3f83e1">
<img width="838" alt="image" src="https://github.com/user-attachments/assets/c36386c7-9b8a-4760-97b7-a98f59dc4242">

**Comment by RoleWong** [comment]
收到, 已修复
