### ISSUE TITLE
send emoji error - 发送表情异常

### ISSUE THREAD

**Issue by lonyee1989** [TencentCloud/chat-uikit-flutter#6]
1、默认的类QQ表情 - 无删除按钮 / 输入框区域【发送】长亮---出现2个发送按钮，点击表情 >文字 输入框> 点击表情>底部发送，面板不会关闭；在点击表情就数组越界异常

2、emoji表情 - 点击表情 > 文字 输入框> 点击表情> 底部发送，面板不会关闭；在点击表情就数组越界异常（eq. 删除按钮真TM丑）||||||||| 点击表情 > 底部发送，面板不会关闭，在点击表情就数组越界异常

3、自定义小表情 - 点击表情底部发送，面板不会关闭；在点击表情就数组越界异常

**Comment by RoleWong** [comment]
> 1、默认的类QQ表情 - 无删除按钮 / 输入框区域【发送】长亮---出现2个发送按钮，点击表情 >文字 输入框> 点击表情>底部发送，面板不会关闭；在点击表情就数组越界异常
> 
> 2、emoji表情 - 点击表情 > 文字 输入框> 点击表情> 底部发送，面板不会关闭；在点击表情就数组越界异常（eq. 删除按钮真TM丑）||||||||| 点击表情 > 底部发送，面板不会关闭，在点击表情就数组越界异常
> 
> 3、自定义小表情 - 点击表情底部发送，面板不会关闭；在点击表情就数组越界异常

1. 
 (a) 无删除按钮的问题，是由于为了和QQ保持一致，他们也没有。
 (b) 输入框区域【发送】长亮，此问题没有复现出来。没有测试出来两个发送按钮。
 (c) 数组越界异常，已复现，我们在下个版本修复。

2. 
 (a) 数组越界异常，已复现，我们在下个版本修复。
 (b) 这个丑的按钮，我们下个版本改的好看点，谢谢反馈。

3. 数组越界异常，已复现，我们在下个版本修复。

再次感谢您的反馈。

**Comment by lonyee1989** [comment]
谢谢🙏 修正

a)可能我用了个盗版的QQ，才会有删除按钮（如图）
b) 对于QQ表情的问题，确实存在两个发送按钮状况    点击几个表情> 点输入框 > 点开表情面板 ===2个发送。
--------


![695003b5ae68585538e20c39b89f50d0](https://user-images.githubusercontent.com/9815235/219258211-c3ff27fd-f142-4304-8b5d-7427337cb05d.jpg)

**Comment by RoleWong** [comment]
> 谢谢🙏 修正
> 
> a)可能我用了个盗版的QQ，才会有删除按钮（如图） b) 对于QQ表情的问题，确实存在两个发送按钮状况 点击几个表情> 点输入框 > 点开表情面板 ===2个发送。
> 
> ## 建议与微信/QQ一样 只保留输入区域那的【发送】，底下不用再弄个发送按钮
> ![695003b5ae68585538e20c39b89f50d0](https://user-images.githubusercontent.com/9815235/219258211-c3ff27fd-f142-4304-8b5d-7427337cb05d.jpg)

下个版本预计在下周发布，数组问题会得以修复。

删除按钮，这个我们排期加一下，预计三月的大版本。

b) 对于QQ表情的问题，确实存在两个发送按钮状况 点击几个表情> 点输入框 > 点开表情面板 ===2个发送。

这个我们确实没办法复现，您要不加我微信：szwangrunlin，然后录屏发我一下呢？我直接看看

**Comment by RoleWong** [comment]
我明白你的意思了，两个发送按钮，指的是上面一个，下面一个。

我之前以为是 下面渲染出了两个发送按钮。

你说的这个场景是我们原来交互的一个feature，我们内部讨论下，看看优化方案。

谢谢您的反馈
