### ISSUE TITLE
会话相关问题

### ISSUE THREAD

**Issue by lonyee1989** [TencentCloud/chat-uikit-flutter#7]
1、会话列表昵称字体大小不能设置

2、聊天对话框页面，appBar默认模式设置的背景颜色无效

3、聊天对话框页面为什么不会自动获取会话名称？如非会话列表进入就得单独写逻辑在获取，为啥不封装好要多此一举

**Comment by RoleWong** [comment]
> 1、会话列表昵称字体大小不能设置
> 
> 2、聊天对话框页面，appBar默认模式设置的背景颜色无效
> 
> 3、聊天对话框页面为什么不会自动获取会话名称？如非会话列表进入就得单独写逻辑在获取，为啥不封装好要多此一举

1. 会话列表的字体大小，我们内部讨论下，看看有没有合适的解决方案。
2. 这个颜色需要通过如下代码定义
```dart
 appBarConfig: AppBar(
            backgroundColor:
                hexToColor("f2f3f5"),
            textTheme: TextTheme(
                titleMedium:
                    TextStyle(color: hexToColor("010000"), fontSize: 16)),
```
3. 在2023年农历新年后的版本，已支持通过传入`conversation`至TIMUIKitChat，来实现自动conversationID和title展示名称。可以升级使用。

**Comment by lonyee1989** [comment]
2、使用这种方式就摒弃了标准文档里的颜色配置方案：
        // chatHeaderBgColor:
        // chatHeaderTitleTextColor: 
        // chatHeaderBackTextColor: 
        // chatHeaderActionTextColor: 
   建议兼容这类方案，同时扩展出参数 actions:[]，方便默认情况下的不做AppBar自定义

3、您提供的方案仅限于通过conversation进入聊天对话，实际使用中基本是通过资料也点【发消息】，或者其他功能页面 如：动态/活动或其他引导性页面，此类页面不利于在uikit下的头部昵称显示

**Comment by lonyee1989** [comment]
1、建议增加属性：会话列表昵称字体大小调整成16或可自定义，单独放出设置头像模块的自定义（业务可能需要圆角/异行/头像框/标签等）

**Comment by RoleWong** [comment]
> 2、使用这种方式就摒弃了标准文档里的颜色配置方案： // chatHeaderBgColor: // chatHeaderTitleTextColor: // chatHeaderBackTextColor: // chatHeaderActionTextColor: 建议兼容这类方案，同时扩展出参数 actions:[]，方便默认情况下的不做AppBar自定义
> 
> 3、您提供的方案仅限于通过conversation进入聊天对话，实际使用中基本是通过资料也点【发消息】，或者其他功能页面 如：动态/活动或其他引导性页面，此类页面不利于在uikit下的头部昵称显示

关于第三点，抱歉早上的回复有误。这个 conversation 字段，已做完，但还没发布，会跟着下一个版本发布。如果从资料也点【发消息】，你可以调用SDK的getConversation方法，先获取到conversation，再跳转进入。

**Comment by RoleWong** [comment]
> 1、建议增加属性：会话列表昵称字体大小调整成16或可自定义，单独放出设置头像模块的自定义（业务可能需要圆角/异行/头像框/标签等）

这个我们内部讨论了下，决定在三月份的2.0大版本中改进。届时，定义字体大小就像现在定义颜色一样简单。谢谢您的建议
