### ISSUE TITLE
pub 相同第三方插件冲突

### ISSUE THREAD

**Issue by Jokergz** [TencentCloud/chat-uikit-flutter#8]
flutter pub add tencent_cloud_chat_uikit
Because every version of tencent_cloud_chat_uikit depends on package_info_plus ^1.4.0 and cns depends on package_info_plus ^3.0.3, tencent_cloud_chat_uikit is forbidden.
So, because cns depends on tencent_cloud_chat_uikit any, version solving failed.

哥们 里边引入的pub 插件 不更新的吗？
package_info_plus 都 3.0了。你里边还引入的1.0的

还有其他的

**Comment by RoleWong** [comment]
反馈收到，我们下个版本，将这些插件统一升级下。

建议您先采用 dependencies_overides 的方式，强制使得版本保持一致

**Comment by onlyYU** [comment]
哥哥，好多好多库版本都落后太多了。。。
当然，还是要感谢作者

**Comment by RoleWong** [comment]
看了一下，主要冲突为 device_info_plus 和 ffi。
建议这两个package，在你们项目的 pubspec.yaml 里面，使用 dependencies_overiide，固定一个版本即可。
因为，如果我们将ffi和device_info_plus升级到最新后，将不再能支持Flutter2系列，所以我们没办法直接升上去。

**Comment by RoleWong** [comment]
> 看了一下，主要冲突为 device_info_plus 和 ffi。 建议这两个package，在你们项目的 pubspec.yaml 里面，使用 dependencies_overiide，固定一个版本即可。
> 
> 因为，如果我们将ffi和device_info_plus升级到最新后，将不再能支持Flutter2系列，所以我们没办法直接升上去。
> 
> 感谢理解～

看了一下，主要冲突为 device_info_plus 和 ffi。
建议这两个package，在你们项目的 pubspec.yaml 里面，使用 dependencies_overiide，固定一个版本即可。

因为，如果我们将ffi和device_info_plus升级到最新后，将不再能支持Flutter2系列，所以我们没办法直接升上去。

感谢理解～
